encoding: utf-8

plugins:
  - jekyll-regex-replace

# SEO相关信息
title: Oyst3r 's Blog
description: Oyst3r 的个人博客
keywords: Oyst3r,Blog,Java,Html,JavaScript
author: Oyst3r
footerText: 'Copyright © 晋ICP备2023018211号-1'

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'blog.sh']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: 'https://clicking777.top'
baseurl: ''

# 菜单
# 必填字段 title: '文本' url: '链接'
# 可选字段 target: '_blank' 新页面打开 
menu:
  - title: 首页
    url: /
  - title: 归类
    url: /pages/categories.html
  - title: 搜索
    url: /pages/search.html
  - title: 友链
    url: /pages/links.html
  - title: 关于
    url: /pages/about.html

# hexo-renderer-marked插件配置
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    langPrefix: language-
    linkify: true
    typographer: true
    quotes: '""'''''

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: false

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: false

# 显示访问量统计，由不蒜子提供服务
extCount: false

# 友情链接
links:
  - title: 36kun的博客
    url: https://www.baidu.com
  - title: drun1baby师傅
    url: https://drun1baby.top/
  - title: 实验室的集美
    url: https://leaderchen007.github.io/
  - title: RT
    url: https://pizz33.github.io/
  - title: Crypto 佬儿
    url: https://dexterjie.github.io/about/
  - title: 橙北橙
    url: http://ehpolestar.com:9999